apiVersion: v1
kind: Service
metadata:
  name: cockroachdb
  labels:
    app: cockroachdb
spec:
  clusterIP: None
  selector:
    app: cockroachdb
  ports:
    - name: sql
      port: 8895
      targetPort: 8895
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb
  labels:
    app: cockroachdb
spec:
  serviceName: cockroachdb
  replicas: 1
  selector:
    matchLabels:
      app: cockroachdb
  template:
    metadata:
      labels:
        app: cockroachdb
    spec:
      containers:
        - name: cockroach
          image: cockroachdb/cockroach:v22.2.19
          command: ["cockroach"]
          args:
            - "start-single-node"
            - "--insecure"
            - "--listen-addr=127.0.0.1:8895"
            - "--store=/data"
          ports:
            - name: sql
              containerPort: 8895
          volumeMounts:
            - name: cdb-data-pv
              mountPath: /data
      terminationGracePeriodSeconds: 60
  volumeClaimTemplates:
    - metadata:
        name: cdb-data-pv
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cdb-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /var/lib/containerd/cdb/            