apiVersion: v1
kind: Pod
metadata:
  name: tailscale-subnet
spec:
  serviceAccountName: tailscale
  containers:
    - name: tailscale
      image: ghcr.io/tailscale/tailscale:latest
      env:
        - name: TS_KUBE_SECRET
          value: tailscale-auth
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTHKEY
        - name: TS_ROUTES
          value: "10.244.0.0/24,10.96.0.0/12"
        - name: TS_USERSPACE
          value: "true"
      securityContext:
        # Run as a non-root user to mitigate privilege escalation attack attempts
        runAsUser: 1000
        runAsGroup: 1000
