apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- jsdoc.yaml
images:
- digest: sha256:e85cb4574b6241b2c83e15fd01b51289d5a66215bf68e680ce4d7f2e4d55a8cb
  name: us-east1-docker.pkg.dev/api-project-146332866891/goldmine/jsdoc@*
  newName: us-east1-docker.pkg.dev/api-project-146332866891/goldmine/jsdoc
# Allows setting the digest via the command-line:
#
#    kustomize edit set image "us-east1-docker.pkg.dev/api-project-146332866891/goldmine/jsdoc@*=us-east1-docker.pkg.dev/api-project-146332866891/goldmine/jsdoc@sha256:e85cb4574b6241b2c83e15fd01b51289d5a66215bf68e680ce4d7f2e4d55a8cb"
#
# To apply:
#
#    kubectl apply -k .