apiVersion: v1
kind: Service
metadata:
  name: ci-workflow
  labels:
    app: ci-workflow
spec:
  selector:
    app: ci-workflow
  ports:
    - name: web
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-workflow
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ci-workflow  # Pod template's label selector
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '20000'        
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ci-workflow
          image: ghcr.io/goldmine-build/ci_workflow_server:2026-01-02T17_57_11Z-jcgregorio-8860ed9-dirty
          args:
            - "--port=:8000"
            - "--pprof_port=:9000"
            - "--prom_port=:20000"
            - "--checkout_dir=/tmp/goldmine"
            - "--pat_path=/etc/github-ci-status/secret"
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 9000
              name: pprof
            - containerPort: 10000
              name: healthz
            - containerPort: 20000
              name: metrics
          volumeMounts:
            - name: github-ci-status
              mountPath: /etc/github-ci-status/
            - name: bazelrc
              mountPath: /etc/bazel/
            - name: gold-github-creds
              mountPath: /usr/local/share/gold-github-creds            
          env:
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BAZELRC
              value: /etc/bazel/.bazelrc
          resources:
            requests:
              memory: "10Gi"
              cpu: "10"
              ephemeral-storage: '1G'
            limits:
              memory: "15Gi"
              cpu: "11"
              ephemeral-storage: '2G'
          readinessProbe:
            httpGet:
              path: /metrics
              port: 20000
            initialDelaySeconds: 3
            periodSeconds: 1
      volumes:
        - name: github-ci-status
          configMap:
            defaultMode: 400
            name: github-ci-status
        - name: gold-github-creds
          configMap:
            defaultMode: 400
            name: gold-github-creds
        - name: bazelrc
          configMap:
            defaultMode: 400
            name: bazelrc
          
